/**:
  ros__parameters:
    wheel_radius:  # The radius of the wheel, primarily used for dead reckoning.
    wheel_width:  # The lateral width of a wheel tire, primarily used for dead reckoning.
    wheel_base: 2.061 # between front wheel center and rear wheel center
    wheel_tread: 1.213 # between left wheel center and right wheel center
    front_overhang: 0.406 # between front wheel center and vehicle front
    rear_overhang: 0.821 # between rear wheel center and vehicle rear
    left_overhang: 0.001 # between left wheel center and vehicle left
    right_overhang: 0.001 # between right wheel center and vehicle right
    vehicle_height: 2.005
    max_steer_angle: 0.349 # [rad]
