/**:
  ros__parameters:
    # Motor controller parameters
    i2c_address: 64
    i2c_busnum: 7
    pwm_freq: 60

    # The publication rate of control commands
    rate: 100.0

    # Debug settings
    enable_debug_publishing: true

    ## PWM parameters
    # The initial PWM value when the vehicle stop.
    init_pwm: 340
    # The minimum PWM value when the vehicle drives backward at the max speed.
    min_pwm: 230
    # The maximum PWM value when the vehicle drives forward at the max speed.
    max_pwm: 460

    ## Ackermann control - longitudinal
    # PID controller parameters for speed control (outer loop)
    kp_speed: 15.0
    ki_speed: 0.0
    kd_speed: 0.05

    # PID controller parameters for acceleration control (inner loop)
    kp_accel: 0.01
    ki_accel: 0.0
    kd_accel: 0.01

    # Maximum acceleration and deceleration constraints [m/s²]
    max_accel: 3.0
    max_decel: 8.0

    ## Ackermann control - steering
    # Maximum steering angle [rad]
    max_steering_angle: 0.5

    # Maximum steering speed [rad/s]
    steering_speed: 1.0

    # The initial value for the steering servo that makes the vehicle go straight.
    init_steer: 400
    # The minimum control value for steering servo making the leftmost turn.
    min_steer: 280
    # The maximum control value for steering servo making the rightmost turn.
    max_steer: 520

    # The ratio between the tire angle and the steer value
    tire_angle_to_steer_ratio: -2000.0
